name: shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hola Mundo"
      - name: multiline script
        run:
          node -v
          npm -v
